### ISSUE TITLE
incorrect action yaml convert when zod string description is empty

### ISSUE THREAD

**Issue by mildronize** [thaitype/actions#2]
### Zod Schema 

```ts
export const githubActionsInputSchema = z.object({
  option: z.string().optional(),
});
```

### Incorrect Output Yaml

```yml
name: Blank
description: Template for creating new actions
runs:
  using: node20
  main: index.cjs
inputs:
  option: {}
```
